### Login to app
POST http://localhost:9001/api/auth/signin
Accept: application/json
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

### Create a new recipe
POST http://localhost:9001/api/recipes
Content-Type: application/json
Accept: application/json

{
  "name": "New Recipe",
  "time": 10,
  "season": "SUMMER",
  "portions": 4,
  "type": "DESSERT",
  "steps": [
    "step1",
    "step2"
  ],
  "ingredients": [
    {
      "name": "ingredient1",
      "quantity": 1,
      "unit": "MILLILITER"
    },
    {
      "name": "ingredient2",
      "quantity": 2.5,
      "unit": "GRAM"
    }
  ]
}

### GET the recipe
GET http://localhost:9001/api/recipes/20
Accept: application/json

### UPDATE the recipe
PUT http://localhost:9001/api/recipes/20
Content-Type: application/json
Accept: application/json

{
  "name": "New Recipe2",
  "time": 102,
  "season": "SUMMER",
  "portions": 42,
  "type": "DESSERT",
  "steps": [
    "step12",
    "step22"
  ],
  "ingredients": [
    {
      "name": "ingredient2",
      "quantity": 2,
      "unit": "MILLILITER"
    },
    {
      "name": "ingredient24",
      "quantity": 2.52,
      "unit": "GRAM"
    }
  ]
}