### GET All Posts
GET http://localhost:9001/api/recipes
Accept: application/json

### GET All Posts
POST http://localhost:9001/api/users/favorites-recipes/6
Accept: application/json

### GET All Posts
DELETE http://localhost:9001/api/users/favorites-recipes/6
Accept: application/json

### GET All Posts
GET http://localhost:9001/api/users/favorites-recipes
Accept: application/json

### GET Post by ID
GET http://localhost:9001/api/recipe/1
Accept: application/json

### GET All Comments of a user
GET http://localhost:9001/api/comments/user/quentin2
Accept: application/json

### GET All Comments of a user
GET http://localhost:9001/api/roles/users/
quentin2
Accept: application/json

### GET All Comments of a user
DELETE http://localhost:9001/api/roles/ROLE_ADMIN/users/1
Accept: application/json

### GET All Comments of a user
GET http://localhost:9001/api/ingredients/recipes/1
Accept: application/json

### sdf
PUT http://localhost:9001/api/ingredients/recipes/4
Content-Type: application/json
Accept: application/json
Cookie: bezkoder-jwt=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJxdWVudGluMiIsImlhdCI6MTcwNzg0NDg1MSwiZXhwIjoxNzA4MTQ0ODUxfQ.Q7WmUGf_mhmMBSo3pZub3mkgBEM9ZpCgeCn6X2wokpA

{
  "quantity": 1,
  "unit": "MILLILITER"
}

### POST Create a new recipe
POST http://localhost:9001/api/recipes
Content-Type: application/json
Accept: application/json

{
  "name": "New Post@",
  "time": 10,
  "season": "SUMMER",
  "portions": 4,
  "steps": [
    "step1",
    "step2"
  ],
  "ingredients": [
    {
      "name": "ingredient1",
      "quantity": 1,
      "unit": "MILLILITER"
    },
    {
      "name": "ingredient2",
      "quantity": 2.5,
      "unit": "GRAM"
    }
  ]
}

### PUT Update a new recipe
PUT http://localhost:9001/api/recipes/1
Content-Type: application/json
Accept: application/json

{
  "name": "New Post@alias",
  "time": 11,
  "season": "SUMMER",
  "portions": 5,
  "steps": [
    "step1alias",
    "step2alis"
  ],
  "ingredients": [
    {
      "name": "ingredient1alias",
      "quantity": 1.01,
      "unit": "CUP"
    },
    {
      "name": "ingredient2alias",
      "quantity": 2.01,
      "unit": "GRAM"
    }
  ]
}


### POST Create a new recipe
POST http://localhost:9001/api/recipes
Content-Type: application/json
Accept: application/json

{
  "name": "New Post@",
  "time": 10,
  "season": "SUMMER",
  "portions": 4,
  "steps": [
    "step1",
    "step2"
  ],
    "ingredients": [
        {
        "name": "ingredient1",
        "quantity": 1,
        "unit": "MILLILITER"
        },
        {
        "name": "ingredient2",
        "quantity": 2.5,
        "unit": "GRAM"
        }
    ]
}


### POST Create a comment
POST http://localhost:9001/api/comments/recipe/1
Content-Type: application/json
Accept: application/json

{
  "text": "New Comment"
}


###
POST http://localhost:9001/api/auth/signup
Accept: application/json
Content-Type: application/json

{
  "username": "quentin2",
  "email": "quentin2@quentin.fr",
  "password": "quentin2",
  "role": ["ROLE_USER"]
}

###
POST http://localhost:9001/api/auth/signin
Accept: application/json
Content-Type: application/json

{
  "username": "quentin2",
  "password": "quentin2"
}

### GET My roles
GET http://localhost:9001/api/roles/users
Accept: application/json


### GET My roles
GET http://localhost:9001/api/auth/me
Accept: application/json

